services:
  - type: web
    name: alpha
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn alpha.wsgi:application
    autoDeploy: true
    preDeployCommand: python manage.py migrate
    plan: free
