services:
  - type: web
    name: alpha
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn alpha.wsgi:application
    envVars:
      - key: DATABASE_URL
        value: "postgresql://gvt_user:uKsps7VsT0JYBlgCZXnXQZyHyOLdsjKt@dpg-d68sabi48b3s73ar1ne0-a/gvt"
      - key: SECRET_KEY
        value: 'django-insecure-b)$00l@!*p_q=$+vzlw6y2oh+9yh+9#7o0mkm1u7_uoi_cbudy'
      - key: DEBUG
        value: "False"
    autoDeploy: true
    plan: free
    deployHook: python manage.py migrate
